# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "dummy"

  config.vm.define :dev01 do |node|
    node.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
      aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
      aws.keypair_name = "aws-key"
  
      aws.instance_type = "t1.micro"
      aws.region = "ap-northeast-1"
  
      # Ubuntu (https://cloud-images.ubuntu.com/locator/ec2/)
      # zone            Name    Version   Arch  Instance Type   Release   AMI-ID        AKI-ID
      # ap-northeast-1  trusty  14.04 LTS amd64 ebs             20141125  ami-42eaed43  aki-176bf516
      aws.ami = "ami-42eaed43"
  
      aws.security_groups = [ 'vagrant' ]
      aws.tags = { 'Name' => 'vagrant-dev' }

      override.ssh.username = 'ubuntu'
      override.ssh.private_key_path = ENV['AWS_SSH_USER_KEY']
    end

    config.vm.provision :ansible do |ansible|
      ansible.playbook = "ansible/common.yml"
    end
  end
end
